name: React Native Build (Alternative)

on:
  workflow_dispatch:

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps

      - name: Setup Expo
        run: npm install -g @expo/cli@latest

      - name: Prebuild Android
        run: npx expo prebuild --platform android

      - name: Make gradlew executable
        run: |
          ls -la android/
          chmod +x android/gradlew
          ls -la android/gradlew

      - name: Build Android APK (with full scan)
        working-directory: ./android
        run: |
          echo "=== GRADLE VERSION SCAN ==="
          ./gradlew --version
          
          echo "=== JAVA VERSION SCAN ==="
          java -version
          javac -version
          
          echo "=== ANDROID SDK SCAN ==="
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
          ls -la $ANDROID_HOME/build-tools/ || echo "No build-tools found"
          
          echo "=== PROJECT DEPENDENCIES SCAN ==="
          ./gradlew dependencies --configuration debugCompileClasspath || echo "Dependencies scan failed"
          
          echo "=== BUILD CONFIGURATION SCAN ==="
          cat app/build.gradle | grep -A 10 -B 10 "compileSdk\|targetSdk\|minSdk" || echo "No SDK config found"
          
          echo "=== STARTING BUILD WITH FULL SCAN ==="
          ./gradlew assembleDebug --scan

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  web-build:
    name: Web Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build for web
        run: npx expo export:web

      - name: Upload web build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist/
